# Generated by Django 5.2.5 on 2025-08-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_BooksAndRelasion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auther',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
